# Seed
seed: 777
memo: xxx

# Path
model_postfix: normalize${normalize}-subgoal${n_subgoal}
data_path: /workspace/expertdata/dttrajectory/
tensorboard_log: /workspace/jaxlog/tensorboard/prior_vae/${model_postfix}
save_path: /workspace/jaxlog/model/prior_vae/${model_postfix}
load_epoch: -1


# Hyperparams
n_subgoal: 3
img_shape: 64
kernel_size: 3
strides: 2
features:
  - 16
  - 32
  - 64
  - 32
  - 16


#total_timestep_per_batch: 1_000_000
total_timestep_per_batch: 250_000
log_interval: 5_000
batch_size: 16
learning_rate: 1e-4
normalize: 255


model:
  _target_: offline_baselines_jax.sopt.CondVaeGoalGenerator
  recon_dim: ${img_shape}
  latent_dim: 10
  dropout: 0

  kernel_size: ${kernel_size}
  strides: ${strides}
  features: ${features}


hydra:
  output_subdir: prior_vae